name: .NET

# Build everything on each push (for now)
on: [push]

env:
  # Required by the setup-msbuild action
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check out wiki
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'patrick-h-schwarz/antme.wiki'
          ref: 'master'
          path: 'antme.wiki'
      - name: simulate
        run: |
            ls
            ./AntMeConsole.exe /folder=./enemies > ./antme.wiki/Result.md
            cd antme.wiki
            cat Result.md
            
            # this is required for the push to succeed
            git config --global user.email "antmegithub-action@elastic.co"
            git config --global user.name "Action AtnmeWiki"
            git add Result.md
            git commit -m "Update Result.md at $(date)"
            git push origin master
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Result
          path: ./antme.wiki/result.md


