name: .NET

# Build everything on each push (for now)
on: [push]

env:
  # Required by the setup-msbuild action
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: simulate
        run: |
            ./AntMeConsole.exe /folder=./../release > result.md
            cat result.md
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Result
          path: result.md


